services:
  - type: web
    name: disasters-web-eco
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: false  # Contrôlé par GitHub Actions
    buildFilter:
      paths:
        - src/**
        - backend/**
        - package.json
        - package-lock.json
        - render.yaml 